# Generated by Django 2.2 on 2019-04-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deck_number_of_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='number_of_cards',
            new_name='card_count',
        ),
    ]
