# Generated by Django 2.2 on 2019-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190403_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(related_name='cards', to='core.Deck'),
        ),
    ]
