# Generated by Django 2.2 on 2019-04-06 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190406_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='scores',
            field=models.ManyToManyField(related_name='card_scores', through='core.Score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='right_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrong_answers',
            field=models.IntegerField(),
        ),
    ]
