# Generated by Django 2.2 on 2019-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190406_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='right_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
