# Generated by Django 2.2 on 2019-04-06 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20190406_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='owners',
            field=models.ManyToManyField(related_name='decks_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
