# Generated by Django 2.2 on 2019-04-07 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deck_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks_authored', to=settings.AUTH_USER_MODEL),
        ),
    ]
