# Generated by Django 2.2 on 2019-04-07 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_card_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owners',
            field=models.ManyToManyField(related_name='cards_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cards_authored', to=settings.AUTH_USER_MODEL),
        ),
    ]
